apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  annotations:
    litmuschaos.io/chaos: "true"
  name: app
  namespace: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: vad1mo/hello-world-rest
        ports:
        - containerPort: 5050